version: "3.9"

services:
  DB:
    image: postgres:15.5
    container_name: stock_db
    volumes:
      - ~/.pg/pg_data/stock:/var/lib/postgresql/data
    env_file:
      - .env
  stocks_products:
    #image: stocks_products:latest
    build:
      dockerfile: Dockerfile
      context: .
    container_name: stocks_django
    depends_on:
      - DB
    volumes:
      - static_volume:/code/static
      - media_volume:/code/media
    env_file:
      - .env
    command: >
      bash -c "python manage.py collectstatic --noinput && python manage.py makemigrations && python manage.py migrate  && gunicorn -b 0.0.0.0:8000 stocks_products.wsgi:application"
  nginx:
    build:
      dockerfile: ./Dockerfile
      context: ./docker/nginx/
    container_name: stocks_nginx
    image: stocks_nginx
    volumes:
      - static_volume:/code/static
      - media_volume:/code/media
    depends_on:
      - stocks_products
    ports:
      - "${NGINX_EXTERNAL_PORT}:80"

volumes:
  static_volume:
  media_volume:
